version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  ma_postgres:
    image: postgres:13.4
    container_name: ma_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./schema_design/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
    env_file:
      - sqlite_to_postgres/.env
    expose:
      - 5432
    ports:
      - "5432:5432"

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es01
    environment:
      - discovery.type=single-node
#      - node.name=es01
#      - cluster.name=es-docker-cluster
#      - discovery.seed_hosts=es02,es03
#      - cluster.initial_master_nodes=es01,es02,es03
#      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
#    networks:
#      - elastic

  ma_web:
    build: .
    restart: always
    container_name: ma_web
    depends_on:
      - ma_postgres
    env_file:
      - movies_admin/.env
    volumes:
      - static_volume:/sites/static/

  ma_nginx:
    image: nginx:1.19.2
    container_name: ma_nginx
    depends_on:
      - ma_web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - static_volume:/sites/static/
    ports:
      - "80:80"